# Site settings
title: Sahas Agro
email: info@sahasagro.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

phone_number: "+91-990-971-7917"
addresss: "Vavdi, Rajkot"
map_url: "https://www.google.co.in/maps/place/22%C2%B014'31.9%22N+70%C2%B047'45.0%22E"
facebook_username: "sahasagroindustries"

# Build settings
markdown: kramdown
